spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.190.132:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#  profiles:
#    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/oms/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 12000
